server:
 port: 8083
 

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
   name: ORDER-SERVICE

eureka:
 instance:
   hostname: localhost
   prefer-ip-address: true
   
client:
     register-with-eureka: true
     fetch-registry: true
service-url:
 default-zone: http://localhost:8761/eureka